version: "3.8"
services:
  
  calculator:
    image: calculator
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - CONFIG_PATH=/go-calculator/config.yaml
    depends_on:
      postgresdb:
        condition: service_healthy
  
  postgresdb:
    image: postgres:16.2
    environment:
      - POSTGRES_DB=calculator
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    logging:
      driver: none
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  
