version: "3.8"
services:
  
  calculator:
    image: calculator
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - CONFIG_PATH=/go-calculator/config.yaml
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - REDIS_PASSWORD=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    depends_on:
      postgresdb:
        condition: service_healthy
      cache:
        condition: service_healthy
  
  postgresdb:
    image: postgres:16.2
    environment:
      - POSTGRES_DB=calculator
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    logging:
      driver: none
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:8
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@user.com
      PGADMIN_DEFAULT_PASSWORD: user
    ports:
      - "5050:80"
    logging:
      driver: none
  
  cache:
    image: redis:6.2-alpine
    restart: always
    command: --loglevel warning
    environment:
      - REDIS_PASSWORD=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      - REDIS_DATABASES=11
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
