version: "3.8"
services:
  
  calculator:
    image: calculator
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3030:3030
    environment:
        - CONFIG_PATH=/go-calculator/config.yaml
