version: "3.8"
services:
  
  calculator:
    image: calculator
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - CONFIG_PATH=/go-calculator/config.yaml
    depends_on:
      - db
  
  db:
    image: postgres:16.2
    environment:
      - POSTGRES_DB=calculator
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    logging:
      driver: none
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:8
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@user.com
      PGADMIN_DEFAULT_PASSWORD: user
    ports:
      - "5050:80"
    logging:
      driver: none
